name: Unit tests on Linux

on:
  push:
    branches: 
      - master
      - features/*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  integration-test:
    name: Run client library unit tests on Linux
    runs-on: [self-hosted, 3shape-ubuntu-latest]
    timeout-minutes: 30

    permissions:
      actions: read
      checks: write # To publish test reports when triggered by Dependabot
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run sample
        shell: pwsh
        working-directory: "./src/CertificateValidatorSample"
        run: dotnet run
